version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"    
  app:
    build: .
    restart: always
    volumes:
      - ".:/app"
    ports: 
      - "3000:3000"
    depends_on:
    - mongo
    command: ["npm", "run", "test"]